<?php
session_start();

/* pega o conteudo do link depois da barra */
/* usado para o menu lateral */
$url = "$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
$url = explode('/', $url)[1];

?>

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Desafio 3</title>
    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="public/assets/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    
    <!-- datatable -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.1.5/css/fixedHeader.bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap.min.css">
</head>

<body>
    <!-- Se tiver mensagem para exibir -->
    <?php
    if (isset($_SESSION["mensagem"])) {
        print_r($_SESSION["mensagem"]);
        ?>
        <script>
            window.onload = function() {
                $('#modalMensagem').modal();
            }
        </script>
    <?php
        $_SESSION["mensagem"] = "";
    }
    ?>

    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar">
            <div class="sidebar-heading"><a class="list-group-item-action" href="/">Desafio 3 - Pravaler</a></div>
            <div class="list-group list-group-flush">
                <a href="/instituicao" class="list-group-item list-group-item-action bg-light <?php if($url == "instituicao") echo "menu-active"?>">Instituição</a>
                <a href="/curso" class="list-group-item list-group-item-action bg-light <?php if($url == "curso") echo "menu-active"?>">Curso</a>
                <a href="/aluno" class="list-group-item list-group-item-action bg-light <?php if($url == "aluno") echo "menu-active"?>">Aluno</a>
            </div>
        </div>
        <!-- fim sidebar -->

        <!-- Conteudo da pagina -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bd-navbar border-bottom">
                <button class="btn btnOcultar" id="menu-toggle">Ocultar</button>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarPrincipal" aria-controls="navbarPrincipal" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-center" id="navbarPrincipal">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#abaListar">Listar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#abaCadastrar">Cadastrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#abaAlterar">Alterar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#abaDeletar">Deletar</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <?= $this->content() ?>
        </div>
        <!-- fim conteudo da pagina -->
    </div>

    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="public/assets/js/script.js"></script>
    <script src="public/assets/js/pgInstituicao.js"></script>
    <script src="public/assets/js/pgCurso.js"></script>
    <script src="public/assets/js/pgAluno.js"></script>

    <!-- validar campos -->
    <script src="public/assets/js/jquery.mask.min.js"></script>
    <script src="public/assets/js/jquery.mask.config.js"></script>
    <script src="public/assets/js/jquery.scripts.config.js"></script>

    <!-- datatables -->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/fixedheader/3.1.5/js/dataTables.fixedHeader.min.js"></script> 
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script> 
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap.min.js"></script> 
</body>

</html>

