<style>
    .nav-tabs {
        display: none;
    }
</style>

<div id="conteudo-principal" class="container-fluid">
    <div class="row">
        <div class="col-md-10 ml-auto mr-auto">
            <h1 class="mt-4">Desafio 3 - SGIE</h1>

            <strong>Selecione uma opção no menu a esquerda</strong>
            <br /><br />
            <p>
                <strong>Descrição:</strong>
            </p>
            <p>
                Este artigo trata-se do planejamento e da organização de um sistema com informações orientadas para a gestão de uma instituição de ensino privada (SGIE).
            </p>
            <p>
                A análise foi feita com base em um modelo de negócio atual, e após a exposição dessas características, foi realizado um esboço preliminar do sistema. Foi identificado no sistema antigo que existia a problemática de duplicação de registros, devido ao grande volume de dados, ajustando-se as tecnologias e realizando algumas mudanças de mercado, novos requisitos funcionais foram levantados para o desenvolvimento de um sistema, bem como alguns desafios confrontados quando se pretende estruturar um sistema robusto e flexível desde o início para a gestão de uma instituição de ensino.
            </p>
            <p>
                Os modelos conceituais propostos são particularmente relevantes para todos aqueles que estão envolvidos nos processos de analisar, modelar, desenvolver e implementar utilizando os sistemas de gestão (ERP).
            </p>
            <p>

            </p>
        </div>
    </div>
</div>