<div class="tab-pane active" id="abaListar" role="tabpanel">
    <div class="row">
        <div class="col-md-10 ml-auto mr-auto">
            <div class="card">
                <div class="card-header text-center">
                    <h5 class="card-title">
                        Listar Instituições
                    </h5>
                    <sup>Escolha uma instituição para listar</sup>
                </div>

                <?php if (!empty($this->view->instituicao)) { ?>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 mr-auto ml-auto">
                                <table id="tabelaResultado" class="table table-striped table-bordered" style="width:100%">
                                    <thead>
                                        <tr>
                                            <th>Instituição</th>
                                            <th>CNPJ</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        <?php
                                            foreach ($this->view->instituicao as $key => $instituicao) { ?>
                                            <tr>
                                                <td><?php echo $instituicao['nome'] ?></td>
                                                <td><?php echo preg_replace("/(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/", "\$1.\$2.\$3/\$4-\$5", $instituicao['cnpj']); ?></td>
                                                <td>
                                                    <?php if ($instituicao['status']) echo "Desativado"; else echo "Ativado"; ?>
                                                </td>
                                            </tr>
                                        <?php
                                            } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                <?php } else { ?>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 col-12 text-center">
                                Não há instituições para listar
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>