<div class="tab-pane active" id="abaListar" role="tabpanel">
    <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
            <div class="card">
                <div class="card-header text-center">
                    <h5 class="card-title">
                        Listar Instituições
                    </h5>
                    <sup>Escolha uma instituição para listar</sup>
                </div>

                <?php if (!empty($this->view->instituicao)) { ?>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8 col-12 mr-auto ml-auto text-center">
                                <select class="form-control" id="listarInstituicaoSelect">
                                    <option selected disabled>Selecione</option>
                                    <?php foreach ($this->view->instituicao as $key => $instituicao) { ?>
                                        <option value="<?php echo $instituicao['cnpj']; ?>" nome="<?php echo $instituicao['nome']; ?>" status="<?php echo $instituicao['status']; ?>">
                                            <?php echo $instituicao['nome']; ?>
                                        </option>
                                    <?php
                                        } ?>
                                </select>
                                <br />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-5 col-6">
                                <div class="form-group">
                                    <label>Instituição</label>
                                    <div id="listarInstituicaoNome" class="form-control">Instituição</div>
                                </div>
                            </div>
                            <div class="col-md-4 col-6">
                                <div class="form-group">
                                    <label>CNPJ</label>
                                    <div id="listarInstituicaoCnpj" type="text" class="form-control">XX.XXX.XXX/XXXX-XX</div>
                                </div>
                            </div>

                            <div class="col-md-3 col-12">
                                <div class="form-group">
                                    <label>Status</label>
                                    <div id="listarInstituicaoStatus" type="text" class="form-control">
                                        Situação
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } else { ?>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12 col-12 text-center">
                                Não há instituições para listar
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>