<div class="tab-pane" id="abaCadastrar" role="tabpanel">
    <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
            <div class="card">
                <div class="card-header text-center">
                    <h5 class="card-title">
                        Cadastrar Instituição
                    </h5>
                    <sup>Cadastre uma nova instituição nos campos abaixo</sup>
                </div>

                <div class="card-body">
                    <form class="needs-validation" action="/instituicaoCadastrar" method="post" enctype="multipart/form-data" id="cadastrarInstituicao" novalidate="">
                        <div class="row">
                            <div class="col-md-5 col-6">
                                <div class="form-group">
                                    <label>Instituição</label>
                                    <input id="instituicaoNome" name="instituicaoNome" type="text" class="form-control" placeholder="Digite o nome da instituição" autocomplete="off" value="" required>
                                    <div class="invalid-feedback">
                                        Insira um nome de instituição válido
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 col-6">
                                <div class="form-group">
                                    <label>CNPJ</label>
                                    <input id="instituicaoCNPJ" name="instituicaoCnpj" type="text" class="form-control cnpj" placeholder="__.___.___/____-__" maxlength="14" autocomplete="off" required>
                                    <div class="invalid-feedback">
                                        Insira um CNPJ válido
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-3 col-12">
                                <div class="form-group">
                                    <label>Status</label>
                                    <div class="custom-control custom-checkbox" style="margin-top: 5%">
                                        <input name="instituicaoStatus" type="checkbox" class="custom-control-input" id="instituicaoStatus">
                                        <label class="custom-control-label" for="instituicaoStatus">Desativado</label>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="ml-auto mr-auto">
                                <button id="btnCadastrarInstituicao" type="submit" class="btn btn-primary btn-round">Adicionar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>